# numpy code

In [7]:
import numpy as np
import pandas as pd

In [8]:
np.array([(2,3,4), [4,5,6]])

array([[2, 3, 4],
       [4, 5, 6]])

In [9]:
np.empty(5)

array([1.72723371e-077, 2.32034860e+077, 3.45845952e-323, 0.00000000e+000,
       0.00000000e+000])

In [10]:
np.empty((5,4)) # but data is filled with garbage

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        4.05620724e+174],
       [1.72723371e-077, 1.72723371e-077, 4.44659081e-323,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [11]:
np.ones((5, 5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
# random numbers between [0.0, 1.0)
np.random.random((5,4))

array([[0.29694089, 0.33636388, 0.32509789, 0.6470454 ],
       [0.55102524, 0.13782761, 0.06371593, 0.9370028 ],
       [0.01870229, 0.53973534, 0.47068225, 0.15675071],
       [0.14963484, 0.53680967, 0.11029616, 0.09831476],
       [0.01491022, 0.4527732 , 0.73997228, 0.96592447]])

In [13]:
# slight variant to above code
np.random.rand(5,4) #function args but not a tuple like before

array([[0.20577002, 0.749083  , 0.64764541, 0.30757214],
       [0.06222281, 0.06515647, 0.87451334, 0.9259674 ],
       [0.55822106, 0.1216536 , 0.83691852, 0.67297767],
       [0.60633291, 0.33173697, 0.37202602, 0.7646733 ],
       [0.61122276, 0.8340443 , 0.20153183, 0.70199835]])

In [14]:
# both rand and random samples from uniform distribution between 0 & 1. Want different distribution?
np.random.normal(size=(5,2)) # a normal distribution!

array([[-1.59612448,  1.18778347],
       [-1.30629191,  0.50453563],
       [-0.19219753,  1.81094721],
       [ 1.42083334, -0.51604539],
       [ 0.55584933,  0.55341038]])

In [15]:
np.random.randint(0,10, size=(6,7)) # to generte ints

array([[8, 0, 5, 4, 6, 1, 5],
       [4, 3, 4, 9, 2, 2, 5],
       [1, 4, 9, 0, 1, 7, 1],
       [3, 2, 3, 1, 6, 7, 5],
       [1, 7, 9, 1, 3, 2, 5],
       [8, 4, 5, 7, 4, 1, 1]])

In [16]:
a = np.random.randint(0,10, size=(6,7))
a.shape

(6, 7)

In [17]:
shape = f"{a.shape[0]}; {a.shape[1]}"
shape

'6; 7'

In [18]:
len(a.shape)  # this gives us the dimension of the data

2

In [19]:
a.ndim # or you could use ndim and ask for the dimension

2

In [20]:
# how do I get number of elements in an array with varying dimension
data = np.random.randint(0,10, size=(2,4,8))
print(data.size)  # get the # of elements
print(data.dtype) # how about data type?

64
int64


In [21]:
a = np.random.randint(0,10, size=(5,6))
a

array([[5, 3, 4, 9, 1, 8],
       [2, 2, 2, 8, 6, 9],
       [8, 8, 2, 7, 2, 3],
       [5, 9, 7, 0, 4, 2],
       [0, 9, 7, 1, 5, 3]])

In [22]:
a.sum(axis=0) # sum per column; 6 cols and therefore 6 values

array([20, 31, 22, 25, 18, 25])

In [23]:
a.sum(axis=1) # sum per rows; 5 rows results in 5 values

array([30, 29, 30, 27, 25])

In [24]:
a.min(axis=0)

array([0, 2, 2, 0, 1, 2])

In [25]:
a.min(axis=1)

array([1, 2, 2, 0, 0])

In [26]:
maxArg = a.argmax()  # to get index with maximum value
actualIndex = np.unravel_index(maxArg, a.shape)  # unravel_index to help out with multi dimension array
value = a[actualIndex]
npMax = a.max()
print(f"maxArg @ {maxArg} & in 2d it is {actualIndex} and value is {value} and numpy max says it is {npMax}")


maxArg @ 3 & in 2d it is (0, 3) and value is 9 and numpy max says it is 9


In [27]:
a = np.random.rand(5)
indices = np.array([1,1,2,3])
print(a)
print(indices)

[0.66184828 0.02450048 0.91562631 0.22935548 0.29593709]
[1 1 2 3]


In [28]:
a[indices]

array([0.02450048, 0.02450048, 0.91562631, 0.22935548])

In [29]:
a = np.random.random(size=(5,4))
a

array([[0.04524269, 0.32082677, 0.38713706, 0.37545279],
       [0.76677866, 0.2820387 , 0.87461276, 0.71007054],
       [0.9286132 , 0.07837283, 0.10324759, 0.89453553],
       [0.4891974 , 0.11121239, 0.77741921, 0.01593809],
       [0.04474911, 0.33217185, 0.23898668, 0.0539698 ]])

In [30]:
a[a<a.mean()]

array([0.04524269, 0.32082677, 0.38713706, 0.37545279, 0.2820387 ,
       0.07837283, 0.10324759, 0.11121239, 0.01593809, 0.04474911,
       0.33217185, 0.23898668, 0.0539698 ])

In [31]:
a<a.mean()

array([[ True,  True,  True,  True],
       [False,  True, False, False],
       [False,  True,  True, False],
       [False,  True, False,  True],
       [ True,  True,  True,  True]])