# numpy code

In [31]:
import numpy as np
import pandas as pd

In [5]:
np.array([(2,3,4), [4,5,6]])

array([[2, 3, 4],
       [4, 5, 6]])

In [14]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.empty((5,4)) # but data is filled with garbage

array([[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000],
       [-1.49166815e-154,  3.11107944e+231,  6.92897965e-310,
         6.92897965e-310],
       [ 6.92897939e-310,  6.92893991e-310,  0.00000000e+000,
         6.92897351e-310]])

In [13]:
np.ones((5, 5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.ndarray?

Init signature: np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer int

In [34]:
# random numbers between [0.0, 1.0)
np.random.normal(size=(5,2))

array([[-0.63814051, -0.10007044],
       [ 0.61008795, -1.29511465],
       [-0.50057485,  0.80127903],
       [-0.32783752,  1.60355606],
       [-1.18989723, -0.35379374]])

In [36]:
np.random.randint(0,10, size=(6,7))

array([[0, 9, 7, 0, 0, 4, 2],
       [7, 2, 7, 0, 3, 6, 6],
       [1, 5, 7, 3, 8, 9, 2],
       [8, 6, 5, 2, 7, 4, 7],
       [9, 4, 6, 2, 2, 7, 2],
       [4, 3, 2, 5, 4, 4, 5]])

In [38]:
a = np.random.randint(0,10, size=(6,7))
a.shape

(6, 7)

In [40]:
shape = f"{a.shape[0]}; {a.shape[1]}"
shape

'6; 7'

In [41]:
len(a.shape)

2

In [45]:
np.random.randint(0,10, size=(2,4,8)).size

64

In [54]:
a = np.random.randint(0,10, size=(5,6))
a

array([[8, 8, 2, 1, 0, 4],
       [4, 7, 4, 5, 0, 7],
       [4, 3, 4, 8, 5, 0],
       [7, 4, 9, 0, 0, 2],
       [9, 7, 2, 5, 9, 6]])

In [55]:
a.sum(axis=0)

array([32, 29, 21, 19, 14, 19])

In [56]:
a.sum(axis=1)

array([23, 27, 24, 22, 38])

In [57]:
a.min(axis=0)

array([4, 3, 2, 0, 0, 0])

In [58]:
a.min(axis=1)

array([0, 0, 0, 0, 2])

In [63]:
maxArg = a.argmax()
actualIndex = np.unravel_index(maxArg, a.shape)  # unravel_index
value = a[actualIndex]
npMax = a.max()
print(f"maxArg @ {maxArg} & in 2d it is {actualIndex} and value is {value} and numpy says it is {npMax}")


maxArg @ 20 & in 2d it is (3, 2) and value is 9 and numpy says it is 9


In [70]:
a = np.random.rand(5)
indices = np.array([1,1,2,3])

In [71]:
a[indices]

array([0.37904588, 0.37904588, 0.23896795, 0.16578745])

In [73]:
a = np.random.random(size=(5,4))
a

array([[0.51882651, 0.4025356 , 0.71960286, 0.44187629],
       [0.8107535 , 0.50862362, 0.65016514, 0.26530708],
       [0.25608348, 0.9580637 , 0.94825705, 0.89331808],
       [0.49961558, 0.09978326, 0.2598308 , 0.95164111],
       [0.7962027 , 0.22450035, 0.7412927 , 0.45930813]])

In [76]:
a[a<a.mean()]

array([0.51882651, 0.4025356 , 0.44187629, 0.50862362, 0.26530708,
       0.25608348, 0.49961558, 0.09978326, 0.2598308 , 0.22450035,
       0.45930813])

In [77]:
a<a.mean()

array([[ True,  True, False,  True],
       [False,  True, False,  True],
       [ True, False, False, False],
       [ True,  True,  True, False],
       [False,  True, False,  True]])